---
title: "pivot_lobsters"
author: "Yevhen Barshchevskyi"
date_modifited: 21/01/2021
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r}
#install.packages('skimr')
#install.packages('kableExtra')
library(tidyverse)
library(readxl)
library(here)
library(skimr)  
library(kableExtra)  

```
```{r}
## Reading lobsters data with skip rows

lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip=4)

```

```{r}
## Exploring data with skimr

skim(lobsters)

```

```{r echo=FALSE}
##PivotTables

siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year=n(),
            mean_size_mm=mean(size_mm, na.rm=TRUE),
            sd_size_mm=sd(size_mm, na.rm=TRUE))

siteyear_summary

##Kable Table Formatting

siteyear_summary %>% kable()

```

```{r}
## Plot lobster mean size by site & year

lobbysize <- ggplot(siteyear_summary, aes(x=year, y=mean_size_mm, color=site))+geom_line()

lobbysize


ggsave(here("figures", "lobsters-line.png"))
```

```{r}
##Using mutate function to change the dataframe & select to select columns

lobsters_detailed <- lobsters %>%
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Allison Horst")

lobsters_detailed %>% 
  select(date, site, size_mm)

```