---
title: "merge.rmd"
output: html_document
author: "Yevhen Barshchevskyi"
date_modified: "21/01/2021"
---

```{r}
library(tidyverse)
library(here)
library(kableExtra)
library(readxl)


```

```{r}
# Read in data: 
fish <- read_csv(here("data", "fish.csv"))
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")

```

```{r}
##Use filter functions

fish_garibaldi <- fish %>% filter(common_name=="garibaldi")

fish_over50 <- fish %>% 
  filter(total_count >= 50)

fish_3sp <- fish %>% 
  filter(common_name %in% c("garibaldi", "blacksmith", "black surfperch"))

fish_gar_2016 <- fish %>% 
  filter(year == 2016 | common_name == "garibaldi")

# Use the ampersand (&) to add another condition "and this must be true":

aque_2018 <- fish %>% 
  filter(year == 2018 & site == "aque")

#Filtering by string pattern

fish_bl <- fish %>% 
  filter(str_detect(common_name, pattern = "black"))

```

```{r}
##Dataset joining

my_fish_join <- fish %>% 
  filter(year == 2017, site == "abur") %>% 
  left_join(kelp_abur, by = c("year", "site")) %>% 
  mutate(fish_per_frond = total_count / total_fronds)

my_fish_join %>% 
  kable() %>% 
  kable_styling(bootstrap_options = "striped", 
                full_width = FALSE)
```