---
title: "Ggplot-analysis"
author: "Yevhen Barshchevskyi"
date_modified: "21/01/2021"
output: html_document
---

```{r}
library(tidyverse)
#install.packages("readxl") 
library(readxl)
library(here)
library(readxl)
```
```{r}
## Reading data file
ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r}
## My first plot
## Define theme default style
#theme_set(theme_minimal())

gg_base <- ggplot(ci_np, aes(x=year, y=visitors))

gg_base + 
  geom_point(aes(size=visitors, color=visitors), alpha=0.5)
```

```{r}
##My second plot

gg_base+geom_col(aes(fill=visitors))

```

```{r}
library(scales)


##Changed y-axis values to numeric instead of scientific
gg_base + geom_line(linetype="dotted") + labs(x="Year", y="Annual park visitors", 
                                              title="Channel Islands NP Visitation", 
                                              subtitle = "(1963-2016") + scale_y_continuous(labels = comma)

```

```{r}
##Combining multiple layers

gg_base+geom_line(color="purple")+geom_point(aes(size=visitors),color="orange", alpha=0.5)


```

```{r}
## Visualizing multiple series of graphs

gg_base2 <- ggplot(ca_np, aes(x=year, y=visitors, group=park_name))

gg_base2 + geom_line(aes(color=park_name))+ scale_y_continuous(labels = comma)


```

```{r}

##Faceting graphs

gg_base2 + geom_line(show.legend = FALSE) + labs(x="Year", y="Annual park visitors") + 
  facet_wrap(~park_name) + scale_y_continuous(labels = comma)

##Saving plot to local folder

ggsave(here("figures", "np_graph.png"), dpi = 180, width = 8, height = 7)

```