---
title: "making-tidy.rmd"
author: "Yevhen Barshchevskyi"
date_modified: "22/01/2021"
output: html_document
---

```{r}
##Loading libraries
#install.packages("janitor")

library(tidyverse)
library(here)
library(janitor)
library(readxl)


```

```{r}
##Read data from excel

inverts <- read_excel(here("data", "inverts.xlsx"))

summary(inverts)
```

```{r}
##Transform data from wide formate to long format

inverts_long <- pivot_longer(data = inverts, 
                                    cols = '2016':'2018',
                                    names_to = "year",
                                    values_to = "sp_count")
class(inverts_long$year)
```

```{r}
##Converting years to numeric

inverts_long <- inverts_long %>% mutate(year=as.numeric(year))

class(inverts_long$year)


```

```{r}
##Converting from long to wider format

inverts_wide <- pivot_wider(inverts_long, names_from = common_name, values_from = sp_count)

##One type formatting for column names

inverts_wide <- inverts_wide %>% clean_names()

##Tried dedupes function

inverts_wide %>% get_dupes(site)
```

```{r}
##Uniting and splitting different columns

inverts_unite <- inverts_long %>% unite(col="site_year", c(site, year), sep="_")

inverst_sep <- inverts_unite %>% separate(site_year, into=c("my_site", "my_year"))

##Replacing text string with patter specified by column name
ca_abbr <- inverts %>% 
  mutate(
    common_name = 
      str_replace(common_name, 
              pattern = "california", 
              replacement = "CA")
  )
```